/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ibfb.lists.core.importwizard;

import ibfb.settings.core.FieldbookSettings;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.cimmyt.cril.ibwb.api.AppServicesProxy;
import org.cimmyt.cril.ibwb.commongui.ConvertUtils;
import org.cimmyt.cril.ibwb.domain.Listnms;
import org.cimmyt.cril.ibwb.domain.Udflds;
import org.openide.util.NbBundle;

public final class ImportGermplasmVisualPanel3 extends JPanel {

    private ResourceBundle bundle = NbBundle.getBundle(ImportGermplasmVisualPanel3.class);

    /**
     * Creates new form ImportGermplasmVisualPanel3
     */
    public ImportGermplasmVisualPanel3() {
        initComponents();
        initValues();
        fillListTypeCombobox();
    }

    private void initValues() {
        dtDate.setDate(new java.util.Date());
    }

    private void fillListTypeCombobox() {
        List<Udflds> udfldList = AppServicesProxy.getDefault().appServices().getUdfldsList(Udflds.LISTNMS_TABLE, Udflds.LISTNMS_FIELD);
        DefaultComboBoxModel dcbmList = (DefaultComboBoxModel) cboListType.getModel();
        Udflds defaultListTypeToSelect = null;

        dcbmList.removeAllElements();

        for (Udflds udflds : udfldList) {
            dcbmList.addElement(udflds);
            if (udflds.getFldno().equals(Udflds.LISTNMS_DEFAULT_TYPE)) {
                defaultListTypeToSelect = udflds;
            }
        }
        // if default name found
        if (defaultListTypeToSelect != null) {
            dcbmList.setSelectedItem(defaultListTypeToSelect);
        }
    }

    @Override
    public String getName() {
        return bundle.getString("ImportGermplasmVisualPanel3.title");
    }

    public Listnms getListnms() {
        Listnms listnms = new Listnms();
        Integer loggedUserid = AppServicesProxy.getDefault().appServices().getLoggedUserId(FieldbookSettings.getLocalGmsUserId());
        // get selected list type
        Udflds selectedListType = (Udflds) cboListType.getSelectedItem();

        listnms.setListname(txtListName.getText());
        listnms.setListdesc(txtDescription.getText());
        listnms.setListdate(ConvertUtils.getDateAsInteger(dtDate.getDate()));
        listnms.setListtype(selectedListType.getFcode());
        listnms.setListuid(loggedUserid);        
        listnms.setLhierarchy(0);
        listnms.setListstatus(Listnms.LSSTATUS_OPEN_LIST);

        return listnms;
    }

    public JTextField getTxtDescription() {
        return txtDescription;
    }

    public JTextField getTxtListName() {
        return txtListName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListName = new javax.swing.JLabel();
        lblDesription = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        txtListName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        cboListType = new javax.swing.JComboBox();
        lblDate = new javax.swing.JLabel();
        dtDate = new com.toedter.calendar.JDateChooser();

        org.openide.awt.Mnemonics.setLocalizedText(lblListName, org.openide.util.NbBundle.getMessage(ImportGermplasmVisualPanel3.class, "ImportGermplasmVisualPanel3.lblListName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblDesription, org.openide.util.NbBundle.getMessage(ImportGermplasmVisualPanel3.class, "ImportGermplasmVisualPanel3.lblDesription.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblType, org.openide.util.NbBundle.getMessage(ImportGermplasmVisualPanel3.class, "ImportGermplasmVisualPanel3.lblType.text")); // NOI18N

        txtListName.setText(org.openide.util.NbBundle.getMessage(ImportGermplasmVisualPanel3.class, "ImportGermplasmVisualPanel3.txtListName.text")); // NOI18N

        txtDescription.setText(org.openide.util.NbBundle.getMessage(ImportGermplasmVisualPanel3.class, "ImportGermplasmVisualPanel3.txtDescription.text")); // NOI18N

        cboListType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(lblDate, org.openide.util.NbBundle.getMessage(ImportGermplasmVisualPanel3.class, "ImportGermplasmVisualPanel3.lblDate.text")); // NOI18N

        dtDate.setToolTipText(org.openide.util.NbBundle.getMessage(ImportGermplasmVisualPanel3.class, "ImportGermplasmVisualPanel3.dtDate.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListName)
                    .addComponent(lblDesription)
                    .addComponent(lblType)
                    .addComponent(lblDate))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtListName, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(cboListType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListName)
                    .addComponent(txtListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cboListType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addGap(0, 202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboListType;
    private com.toedter.calendar.JDateChooser dtDate;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDesription;
    private javax.swing.JLabel lblListName;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtListName;
    // End of variables declaration//GEN-END:variables
}
