/*
 * SelectLocationPanel.java
 *
 * Created on Jul 13, 2011, 3:39:32 PM
 */
package org.cimmyt.cril.ibwb.commongui.select.location;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.cimmyt.cril.ibwb.api.AppServicesProxy;
import org.cimmyt.cril.ibwb.domain.Location;

/**
 *
 * @author tmsanchez
 */
public class SelectLocationPanel extends javax.swing.JPanel {

    private List<Location> countryList;

    private void initComboBoxes() {
        Location locationFilter = new Location(false);
        //locationFilter.setLtype(406);
        locationFilter.setLname(TOOL_TIP_TEXT_KEY);
        countryList = AppServicesProxy.getDefault().appServices().getListLocation(locationFilter, 0, 0, false);

        DefaultComboBoxModel model = (DefaultComboBoxModel) cboCountry.getModel();
        model.removeAllElements();
        for (Location country : countryList) {
            model.addElement(country);
        }

    }

    /** Creates new form SelectLocationPanel */
    public SelectLocationPanel() {
        initComponents();
        initComboBoxes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCountry = new javax.swing.JLabel();
        cboCountry = new javax.swing.JComboBox();
        lblState = new javax.swing.JLabel();
        cboState = new javax.swing.JComboBox();
        lblDistrict = new javax.swing.JLabel();
        cboDistrict = new javax.swing.JComboBox();

        lblCountry.setText(org.openide.util.NbBundle.getMessage(SelectLocationPanel.class, "SelectLocationPanel.lblCountry.text")); // NOI18N

        cboCountry.setModel(new DefaultComboBoxModel());

        lblState.setText(org.openide.util.NbBundle.getMessage(SelectLocationPanel.class, "SelectLocationPanel.lblState.text")); // NOI18N

        cboState.setModel(new DefaultComboBoxModel());

        lblDistrict.setText(org.openide.util.NbBundle.getMessage(SelectLocationPanel.class, "SelectLocationPanel.lblDistrict.text")); // NOI18N

        cboDistrict.setModel(new DefaultComboBoxModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCountry)
                    .addComponent(lblState)
                    .addComponent(lblDistrict))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDistrict, 0, 386, Short.MAX_VALUE)
                    .addComponent(cboState, 0, 386, Short.MAX_VALUE)
                    .addComponent(cboCountry, 0, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(cboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblState)
                    .addComponent(cboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDistrict))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCountry;
    private javax.swing.JComboBox cboDistrict;
    private javax.swing.JComboBox cboState;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDistrict;
    private javax.swing.JLabel lblState;
    // End of variables declaration//GEN-END:variables
}
