/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScaleConPanel.java
 *
 * Created on Apr 13, 2012, 4:18:40 PM
 */
package ibfb.traits.traits;

import org.cimmyt.cril.ibwb.domain.TmsScaleCon;

/**
 *
 * @author TMSANCHEZ
 */
public class ScaleConPanel extends javax.swing.JPanel implements TmsScaleDefCellValue {
    private TmsScaleCon scaleCon;

    /** Creates new form ScaleConPanel */
    public ScaleConPanel(TmsScaleCon scaleCon) {
        this.scaleCon = scaleCon;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblStart = new javax.swing.JLabel();
        txtStartValue = new javax.swing.JTextField();
        txtEndValue = new javax.swing.JTextField();
        lblEndValue = new javax.swing.JLabel();

        lblStart.setText(org.openide.util.NbBundle.getMessage(ScaleConPanel.class, "ScaleConPanel.lblStart.text")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${scaleCon.slevel}"), txtStartValue, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${scaleCon.elevel}"), txtEndValue, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblEndValue.setText(org.openide.util.NbBundle.getMessage(ScaleConPanel.class, "ScaleConPanel.lblEndValue.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblEndValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndValue))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStart)
                    .addComponent(txtStartValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEndValue)
                    .addComponent(txtEndValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEndValue;
    private javax.swing.JLabel lblStart;
    private javax.swing.JTextField txtEndValue;
    private javax.swing.JTextField txtStartValue;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public TmsScaleCon getScaleCon() {
        return scaleCon;
    }

    public void setScaleCon(TmsScaleCon scaleCon) {
        this.scaleCon = scaleCon;
    }

    @Override
    public Object getCellValue() {
        return this.scaleCon;
    }


    
}
