/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScaleDisValuesPanel.java
 *
 * Created on Apr 16, 2012, 3:09:44 PM
 */
package ibfb.traits.traits;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;

/**
 *
 * @author TMSANCHEZ
 */
public class ScaleDisValuesPanel extends javax.swing.JPanel {

    /** Creates new form ScaleDisValuesPanel */
    public ScaleDisValuesPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblValues = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstValues = new javax.swing.JList();

        lblName.setText(org.openide.util.NbBundle.getMessage(ScaleDisValuesPanel.class, "ScaleDisValuesPanel.lblName.text")); // NOI18N

        txtName.setText(org.openide.util.NbBundle.getMessage(ScaleDisValuesPanel.class, "ScaleDisValuesPanel.txtName.text")); // NOI18N

        lblValues.setText(org.openide.util.NbBundle.getMessage(ScaleDisValuesPanel.class, "ScaleDisValuesPanel.lblValues.text")); // NOI18N

        txtValue.setText(org.openide.util.NbBundle.getMessage(ScaleDisValuesPanel.class, "ScaleDisValuesPanel.txtValue.text")); // NOI18N
        txtValue.setToolTipText(org.openide.util.NbBundle.getMessage(ScaleDisValuesPanel.class, "ScaleDisValuesPanel.txtValue.toolTipText")); // NOI18N
        txtValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValueKeyReleased(evt);
            }
        });

        lstValues.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(lstValues);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(26, 26, 26)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblValues)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(txtValue))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValues)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueKeyReleased
        addValueToList(evt);
    }//GEN-LAST:event_txtValueKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblValues;
    private javax.swing.JList lstValues;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
    
    private void addValueToList(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultListModel defaultListModel = (DefaultListModel)lstValues.getModel();
            defaultListModel.addElement(txtValue.getText());
            txtValue.setText("");
        }
    }

}
