/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectionFrame.java
 *
 * Created on May 26, 2011, 11:00:30 AM
 */
package org.cimmyt.cril.ibwb.db.tests;

import org.cimmyt.cril.ibwb.db.options.ConnectionPanel;

/**
 *
 * @author TMSANCHEZ
 */
public class ConnectionFrame extends javax.swing.JFrame {

    ConnectionPanel connectionPanel1 = new ConnectionPanel();
    ConnectionPanel connectionPanel2 = new ConnectionPanel();
    ConnectionPanel connectionPanel3 = new ConnectionPanel();
    ConnectionPanel connectionPanel4 = new ConnectionPanel();
    /** Creates new form ConnectionFrame */
    public ConnectionFrame() {
        initComponents();
        this.add(connectionPanel1);
        this.add(connectionPanel2);
        this.add(connectionPanel3);
        this.add(connectionPanel4);
        this.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 2));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConnectionFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
