
package ibfb.help.core;

import java.awt.BorderLayout;
import javax.help.HelpSet;
import javax.help.JHelp;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;


@ConvertAsProperties(dtd = "-//ibfb.help.core//MyHelp//EN",
autostore = false)
@TopComponent.Description(preferredID = "MyHelpTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "properties", openAtStartup = false)
@ActionID(category = "Window", id = "ibfb.help.core.MyHelpTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_MyHelpAction",
preferredID = "MyHelpTopComponent")

public final class MyHelpTopComponent extends TopComponent {
    
    
    private static JHelp helpViewer = null;
 

    public MyHelpTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(MyHelpTopComponent.class, "CTL_MyHelpTopComponent"));
        setToolTipText(NbBundle.getMessage(MyHelpTopComponent.class, "HINT_MyHelpTopComponent"));
        
        setDisplayName("Help");
        setLayout(new BorderLayout());
        HelpSet help = Lookup.getDefault().lookup(HelpSet.class);
        helpViewer = new JHelp(help);
        add(helpViewer, BorderLayout.CENTER);       
        helpViewer.setNavigatorDisplayed(false);

    }

        public static JHelp getHelpViewer() {
        return helpViewer;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
