/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ibfb.lists.core;

import java.util.List;
import java.util.ResourceBundle;
import org.cimmyt.cril.ibwb.api.AppServicesProxy;
import org.cimmyt.cril.ibwb.commongui.TableBindingUtil;
import org.cimmyt.cril.ibwb.domain.Listnms;
import org.openide.util.NbBundle;

/**
 * Utility Dialog to selecte germplasm lists
 *
 * @author tmsanchez
 */
public class GermplasmSearch extends javax.swing.JPanel {

    private ResourceBundle bundle = NbBundle.getBundle(GermplasmSearch.class);
    private List<Listnms> germplamList;

    /**
     * Creates new form GermplasmSearch
     */
    public GermplasmSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGermplasmList = new javax.swing.JTable();
        lblListsFound = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();

        txtSearch.setText(org.openide.util.NbBundle.getMessage(GermplasmSearch.class, "GermplasmSearch.txtSearch.text")); // NOI18N
        txtSearch.setToolTipText(org.openide.util.NbBundle.getMessage(GermplasmSearch.class, "GermplasmSearch.txtSearch.toolTipText")); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setText(org.openide.util.NbBundle.getMessage(GermplasmSearch.class, "GermplasmSearch.lblSearch.text")); // NOI18N

        tblGermplasmList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGermplasmListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGermplasmList);

        lblListsFound.setText(org.openide.util.NbBundle.getMessage(GermplasmSearch.class, "GermplasmSearch.lblListsFound.text")); // NOI18N

        btnSearch.setText(org.openide.util.NbBundle.getMessage(GermplasmSearch.class, "GermplasmSearch.btnSearch.text")); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblInstructions.setText(org.openide.util.NbBundle.getMessage(GermplasmSearch.class, "GermplasmSearch.lblInstructions.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListsFound)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch))))
                    .addComponent(lblInstructions))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblListsFound)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(77, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        updateListNameTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblGermplasmListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGermplasmListMouseClicked
        if (evt.getClickCount() == 2) {
            //openListDataWindow();
        }
    }//GEN-LAST:event_tblGermplasmListMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        updateListNameTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    public void updateListNameTable() {
        Listnms filter = new Listnms(true);
        filter.setGlobalsearch(txtSearch.getText());
        germplamList = AppServicesProxy.getDefault().appServices().getListListnms(filter, 0, 0, false);
        lblListsFound.setText(germplamList.size() + " " + NbBundle.getMessage(GermplasmSearch.class, "GermplasmSearch.lblListsFound.text"));

        StringBuilder headers = new StringBuilder(bundle.getString("GermplasmSearch.headerListid"));
        headers.append(",");
        headers.append(bundle.getString("GermplasmSearch.headerListname"));
        headers.append(",");
        headers.append(bundle.getString("GermplasmSearch.headerListdesc"));

        TableBindingUtil.createColumnsFromDB(Listnms.class, germplamList, tblGermplasmList, "listid,listname,listdesc", headers.toString());
    }

    /**
     * Get selected row in Grid
     *
     * @return
     */
    public Listnms getSelectedListnms() {
        if (tblGermplasmList.getSelectedRowCount() > 0) {
            return this.germplamList.get(tblGermplasmList.getSelectedRow());
        } else {
            return null;
        }
    }

    public List<Listnms> getGermplamList() {
        return germplamList;
    }

    public void setGermplamList(List<Listnms> germplamList) {
        this.germplamList = germplamList;
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblListsFound;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblGermplasmList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
